BUNDLE_NAME = LastFMScrobblerPrefs
LastFMScrobblerPrefs_FILES = LastFMScrobblerPrefsController.m
LastFMScrobblerPrefs_INSTALL_PATH = /Library/PreferenceBundles
LastFMScrobblerPrefs_FRAMEWORKS = UIKit
LastFMScrobblerPrefs_PRIVATE_FRAMEWORKS = Preferences

# Include the plist files as resources so they get copied to the bundle
LastFMScrobblerPrefs_RESOURCES = LastFMScrobblerPrefs.plist entry.plist

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk