BUNDLE_NAME = LastFMScrobblerPrefs
LastFMScrobblerPrefs_FILES = LastFMScrobblerPrefsController.m
LastFMScrobblerPrefs_INSTALL_PATH = /Library/PreferenceBundles
LastFMScrobblerPrefs_FRAMEWORKS = UIKit
LastFMScrobblerPrefs_PRIVATE_FRAMEWORKS = Preferences

# Include the preference specifiers as a bundle resource
LastFMScrobblerPrefs_RESOURCE_FILES = Info.plist LastFMScrobblerPrefs.plist

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk