BUNDLE_NAME = LastFMScrobblerPrefs
LastFMScrobblerPrefs_FILES = LastFMScrobblerPrefs.plist
LastFMScrobblerPrefs_INSTALL_PATH = /Library/PreferenceBundles
LastFMScrobblerPrefs_FRAMEWORKS = UIKit
LastFMScrobblerPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk